# Grantmaker settings
foundation_name: The Example Foundation
foundation_tagline: Advancing the adoption of open source technology among progressive funders
email_public: hello@example.com

# Social media settings
# Enter the full profile url (e.g. https://twitter.com/smartergiving)
twitter: https://twitter.com/smartergiving
facebook: 
instagram: 
github: https://github.com/smartergiving

# Site settings
# Meta tags
title: # Default's to foundation_name if left blank
description: > # this means to start on the next line (which needs to be indented two spaces)"
  The Example Foundation erat sit proin magnis duis, vulputate wisi vel hac, sed justo turpis leo sit hac mauris, maecenas sem dapibus neque malesuada ante, congue arcu..

# Jekyll settings
collections:
  featured-cards:
    output: true
safe: true # If using Github Pages, it's a good idea to keep this as 'true'
baseurl: "" # Leave this blank unless your site is located on a subpath, e.g. /blog
url: "https://foundation-template.smartergiving.org" # Typically http://www.yourdomain.org


# Build settings
markdown: kramdown
exclude: 
  - README.md
  - /images/photoshop-helpers
